version: "3"

volumes:
  redis:

services:
  redis:
    image: "example/redis:v7.0.4"
    command: ["/app/docker-redis-entrypoint.sh"]
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - redis:/data
      - ./:/app
